apiVersion: v1
data:
  values.yaml: {{ toYaml .Values.components.secrets_distributor.config | nindent 4 }}
kind: ConfigMap
metadata:
  name: secret-distributor-config
  namespace: {{ printf "%s%s" .Values.components.secrets_distributor.namespace .Values.naming.suffix }}