{{- if .Capabilities.APIVersions.Has "secrets-store.csi.x-k8s.io/v1/SecretProviderClass" -}}
{{- if eq .Values.components.secrets_distributor.state "enabled" -}}
{{- if eq .Values.azure.state "enabled"  -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-sync
  namespace: {{ .Values.components.secrets_distributor.namespace }}
  annotations:
    xlscsde.nhs.uk/secretUsage: "Key Vault Sync"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{.Values.azure.client_id }}
    keyvaultName: {{.Values.azure.keyvault_name }}
    tenantId: {{.Values.azure.tenant_id}}
    objects: |
        array:
        - |
          objectName: PrimaryStorageAccountName
          objectType: secret
        - |
          objectName: PrimaryStorageAccountKey
          objectType: secret
        - |
          objectName: JupyterAppRegistrationClientSecret
          objectType: secret
        - |
          objectName: WildcardCertificate
          objectType: secret
        - |
          objectName: WildcardCertificateKey
          objectType: secret
        - |
          objectName: PatToken
          objectType: secret
        - |
          objectName: JupyterCookieSecret
          objectType: secret
        - |
          objectName: OhdsiDbPassword
          objectType: secret
        - |
          objectName: HadesPassword
          objectType: secret
        - |
          objectName: OhdsiAppRegistrationClientSecret
          objectType: secret
        - |
          objectName: GuacDbPassword
          objectType: secret
        - |
          objectName: KeycloakDbUsername
          objectType: secret
        - |
          objectName: KeycloakDbPassword
          objectType: secret
        - |
          objectName: ApacheSupersetAppRegistrationClientSecret
          objectType: secret
        - |
          objectName: ThanosPersistentStoreSecret
          objectType: secret
        {{- range include "flux.secrets" $ | fromJsonArray }}
        - |
          objectName: {{ . }}
          objectType: secret
        {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
