{{- if .Values.components.ingress_nginx.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-applier
  namespace: {{ .Values.components.ingress_nginx.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux.applier.binding.name" .Values.components.ingress_nginx }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: {{ .Values.components.ingress_nginx.namespace }}
{{- end -}}