{{ range .Values.components }}
{{ if hasKey . "repository"}}
{{ if hasKey .repository "name" }}
{{- if eq .state "enabled" -}}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: "{{ printf "%s%s" .repository.name $.Values.naming.suffix }}"
spec:
  interval: 1m0s
  ref:
    branch: "{{ .repository.branch }}"
  timeout: 60s
  url: "{{ .repository.url }}"
{{ if hasKey .repository "requiresAuth" }}
{{ if eq .repository.requiresAuth true }}
  secretRef:
    name: "{{ printf "%s%s-pat-token" .repository.name $.Values.naming.suffix }}"
{{ end }}
{{ end }}
---
{{- end -}}
{{ end }}
{{ end }}
{{ end }}