{{- if .Capabilities.APIVersions.Has "xlscsde.nhs.uk/v1/SecretsDistribution" -}}
{{- if .Values.deployment.includeSecretDistributions -}}
{{- range .Values.components -}}
{{- if hasKey . "repository" -}}
{{- if hasKey .repository "name" -}}
{{- if hasKey .repository "secret" -}}
{{- if hasKey .repository.secret "usernameKey" -}}
{{- if ne .repository.secret.usernameKey "" -}}
{{- if hasKey .repository.secret "passwordKey" -}}
{{- if ne .repository.secret.passwordKeyKey "" -}}

{{- if eq .state "enabled" -}}
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: "{{ printf "%s%s-pat-token" .repository.name $.Values.naming.suffix }}"
  annotations:
    xlscsde.nhs.uk/secretUsage: "Repository PAT Token"
spec:
  name: "{{ printf "%s%s-pat-token" .repository.name $.Values.naming.suffix }}"
  secrets:
  - from: {{ .repository.secret.usernameKey }}
    to: username
  - from: {{ .repository.secret.passwordKey }}
    to: password
---
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
