{{ range .Values.components }}
{{ if hasKey . "repository"}}
{{- if eq .state "enabled" -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: "{{ printf "%s%s" .repository.name  $.Values.naming.suffix  }}"
spec:
  force: false
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: "{{ printf "%s%s" .repository.name $.Values.naming.suffix }}"
    namespace: "{{ $.Release.Namespace }}"
  timeout: 1m0s
  wait: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
    - kind: ConfigMap
      name: {{ include "config.name" $ }}
    - kind: ConfigMap
      name: "{{ printf "environment-configuration%s" $.Values.naming.suffix }}"
    - kind: ConfigMap
      name: "{{ printf "deployment-namespaces%s" $.Values.naming.suffix }}"
---
{{- end -}}
{{ end }}
{{ end }}