{{ range .Values.components }}
{{ if hasKey . "repository "}}
{{- if eq .state "enabled" -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ cat "lscsde-workspace-mgr"  .Values.naming.suffix  }}
spec:
  force: false
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: {{ cat .repository.name $.Values.naming.suffix }}
    namespace: {{ $.Release.Namespace }}
  timeout: 1m0s
  wait: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
    - kind: ConfigMap
      name: {{ include "config.name" $ }}
    - kind: ConfigMap
      name: {{ cat "environment-configuration" .Values.naming.suffix }}
    - kind: ConfigMap
      name: {{ cat "deployment-namespaces" .Values.naming.suffix }}
{{- end -}}
{{ end }}
{{ end }}