azure:
  state: "disabled"
  client_id: ""
  tenant_id: ""
  keyvault_name: ""
  dns:
    subscription_id: ""
    private_dnz_zone: ""
    resource_group: ""

dns:
  prefix: ""

components:
  aks_dns:
    state: "enabled"
    chart_version: ""
  configmap_transformer:
    state: "disabled"
    chart_version: ""
  analytics_workspace_management:
    state: "enabled"
    namespace: lscsde-workspace-mgr
    chart_version: "" 
    repository:
      url: https://github.com/lsc-sde/iac-flux-analytics-workspace-management
      branch: main
  cert_manager:
    state: "enabled"
    namespace: cert-manager
    chart_version: ""
    repository:
      url: https://github.com/lsc-sde/iac-flux-certmanager
      branch: main
  trust_manager:
    state: "enabled"
    namespace: cert-manager
    chart_version: ""
  github_runner:
    state: "disabled"
    namespace: github-runner
    chart_version: ""
    repository:
      url: https://github.com/lsc-sde/iac-flux-github-action-runners
      branch: main
  ingress_nginx:
    state: "enabled"
    namespace: nginx
    chart_version: ""
    repository:
      url: https://github.com/lsc-sde/iac-flux-nginx
      branch: main
  jupyter_hub:
    state: "enabled"
    namespace: jupyterhub
    chart_version: ""
    repository:
      url: https://github.com/lsc-sde/iac-flux-jupyter
      branch: main
  keda:
    state: "enabled"
    namespace: keda
    chart_version: ""
    repository:
      url: https://github.com/lsc-sde/iac-flux-keda
      branch: main
  metrics_server:
    state: "enabled"
    chart_version: ""
    namespace: metrics-server
    repository:
      url: https://kubernetes-sigs.github.io/metrics-server/
  ohdsi:
    state: "enabled"
    namespace: ohdsi
    repository:
      url: https://github.com/lsc-sde/iac-flux-ohdsi
      branch: main
  secrets_distributor:
    state: "enabled"
    namespace: secrets-distributor
    chart_version: ""
  guacamole:
    state: "disabled"
    chart_version: ""
    namespace: guacamole