azure:
  state: "disabled"
  client_id: ""
  tenant_id: ""
  keyvault_name: ""
  dns:
    subscription_id: ""
    private_dnz_zone: ""
    resource_group: ""

dns:
  prefix: ""

naming:
  suffix: ""

components:
  aks_dns:
    state: "enabled"
    chart_version: ""
    namespace: "aks-dns-operator"
  analytics_workspace_management:
    state: "enabled"
    namespace: lscsde-workspace-mgr
    chart_version: "" 
    repository:
      name: analytics-workspace-management
      url: https://github.com/lsc-sde/iac-flux-analytics-workspace-management
      branch: main
  cert_manager:
    state: "enabled"
    namespace: cert-manager
    chart_version: ""
    repository:
      name: certmanager
      url: https://github.com/lsc-sde/iac-flux-certmanager
      branch: main
  trust_manager:
    state: "enabled"
    namespace: cert-manager
    chart_version: ""
  github_runner:
    state: "disabled"
    namespace: github-runner
    chart_version: ""
    repository:
      name: github-runner
      url: https://github.com/lsc-sde/iac-flux-github-action-runners
      branch: main
  ingress_nginx:
    state: "enabled"
    namespace: nginx
    chart_version: ""
    repository:
      name: nginx
      url: https://github.com/lsc-sde/iac-flux-nginx
      branch: main
  jupyter_hub:
    state: "enabled"
    namespace: jupyterhub
    chart_version: ""
    repository:
      name: jupyter
      url: https://github.com/lsc-sde/iac-flux-jupyter
      branch: main
  keda:
    state: "enabled"
    namespace: keda
    chart_version: ""
    repository:
      name: keda
      url: https://github.com/lsc-sde/iac-flux-keda
      branch: main
  metrics_server:
    state: "enabled"
    chart_version: ""
    chart_url: https://kubernetes-sigs.github.io/metrics-server/ 
    namespace: metrics-server
  ohdsi:
    state: "enabled"
    namespace: ohdsi
    repository:
      name: ohdsi
      url: https://github.com/lsc-sde/iac-flux-ohdsi
      branch: main
  secrets_distributor:
    state: "enabled"
    namespace: secrets-distributor
    chart_version: ""
    repository:
      name: secrets-distributor
      url: https://github.com/lsc-sde/iac-flux-secrets-distributor
      branch: main
    config: |-
      volumeMounts:
        - name: secrets-store-inline
          mountPath: /mnt/secrets
          readOnly: true
      volumes:
        - name: secrets-store-inline
          hostPath:
            path: /run/desktop/mnt/host/c/tmp/secrets
            type: Directory
  guacamole:
    state: "disabled"
    chart_version: ""
    namespace: guacamole
    repository:
      name: guacamole
      url: https://github.com/lsc-sde/iac-flux-guacamole
      branch: main
      path: /
  workspace_definitions:
    state: "enabled"
    chart_version: ""
    namespace: workspace-definitions
    repository:
      name: workspace-definitions
      url:  https://github.com/lsc-sde/iac-flux-workspace-definitions
      branch: main
      path: "production"