azure:
  state: "disabled"
  client_id: ""
  tenant_id: ""
  keyvault_name: ""
  dns:
    subscription_id: ""
    private_dnz_zone: ""
    resource_group: ""

dns:
  prefix: ""

naming:
  suffix: ""

deployment:
  includeSecretDistributions: true

components:
  aks_dns:
    state: "enabled"
    chart_version: ""
    namespace: "aks-dns-operator"
  analytics_workspace_management:
    state: "enabled"
    namespace: lscsde-workspace-mgr
    chart_version: "" 
    repository:
      name: analytics-workspace-management
      url: https://github.com/lsc-sde/iac-flux-analytics-workspace-management
      branch: main
      secret:
        requiresAuth: false
        usernameKey: ""
        passwordKey: ""
  cert_manager:
    state: "enabled"
    namespace: cert-manager
    chart_version: ""
    repository:
      name: certmanager
      url: https://github.com/lsc-sde/iac-flux-certmanager
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  trust_manager:
    state: "enabled"
    namespace: cert-manager
    chart_version: ""
  github_runner:
    state: "disabled"
    namespace: github-runner
    chart_version: ""
    repository:
      name: github-runner
      url: https://github.com/lsc-sde/iac-flux-github-action-runners
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  ingress_nginx:
    state: "enabled"
    namespace: nginx
    chart_version: ""
    repository:
      name: nginx
      url: https://github.com/lsc-sde/iac-flux-nginx
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  jupyter_hub:
    state: "enabled"
    namespace: jupyterhub
    chart_version: ""
    repository:
      name: jupyter
      url: https://github.com/lsc-sde/iac-flux-jupyter
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  keda:
    state: "enabled"
    namespace: keda
    chart_version: ""
    repository:
      name: keda
      url: https://github.com/lsc-sde/iac-flux-keda
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  metrics_server:
    state: "enabled"
    chart_version: ""
    chart_url: https://kubernetes-sigs.github.io/metrics-server/ 
    namespace: metrics-server
  ohdsi:
    state: "enabled"
    namespace: ohdsi
    repository:
      name: ohdsi
      url: https://github.com/lsc-sde/iac-flux-ohdsi
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  secrets_distributor:
    state: "enabled"
    namespace: secrets-distributor
    chart_version: ""
    repository:
      name: secrets-distributor
      url: https://github.com/lsc-sde/iac-flux-secrets-distributor
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
    config: |-
      volumeMounts:
        - name: secrets-store-inline
          mountPath: /mnt/secrets
          readOnly: true
      volumes:
        - name: secrets-store-inline
          hostPath:
            path: /run/desktop/mnt/host/c/tmp/secrets
            type: Directory
  keycloak:
    state: "enabled"
    chart_version: ""
    namespace: keycloak
    image: ""
    repository:
      name: keycloak
      url: https://github.com/lsc-sde/iac-flux-keycloak
      branch: main
      path: /cluster/azure/
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  guacamole:
    state: "enabled"
    chart_version: ""
    namespace: guacamole
    repository:
      name: guacamole
      url: https://github.com/lsc-sde/iac-flux-guacamole
      branch: main
      path: /cluster/azure/
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  workspace_definitions:
    state: "enabled"
    chart_version: ""
    namespace: workspace-definitions
    repository:
      name: workspace-definitions
      url:  https://github.com/lsc-sde/iac-flux-example-workspace-definitions
      branch: main
      path: ""
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  superset:
    state: "enabled"
    namespace: superset
    chart_version: ""
    repository:
      name: superset
      url: https://github.com/lsc-sde/iac-flux-apache-superset
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  rabbitmq:
    state: "enabled"
    namespace: rabbitmq
    chart_version: ""
    repository:
      name: rabbitmq
      url: https://github.com/lsc-sde/iac-flux-rabbitmq
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  observability_metrics:
    state: "enabled"
    namespace: observability-metrics
    chart_version: ""
    repository:
      name: observability-metrics
      url: https://github.com/lsc-sde/iac-flux-observability-metrics
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  awms_guacamole:
    state: "enabled"
    chart_version: ""
    namespace: awms-guacamole
    image: ""
    repository:
      name: awms-guacamole
      url: https://github.com/lsc-sde/awms-guacamole-operator
      branch: main
      path: /flux/azure/
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  awms_crate:
    state: "enabled"
    chart_version: ""
    namespace: awms-crate
    image: ""
    repository:
      name: awms-crate
      url: https://github.com/lsc-sde/awms-crate-operator
      branch: main
      path: /flux/azure/
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
  neulander:
    state: "enabled"
    namespace: neulander
    chart_version: ""
    repository:
      name: neulander
      url: https://github.com/lsc-sde/iac-flux-neulander
      branch: main
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""
cr8tor_publisher:
    state: "enabled"
    namespace: cr8tor-publisher
    chart_version: ""
    repository:
      name: cr8tor-publisher
      url: https://github.com/lsc-sde-crates/cr8tor-publisher
      branch: main
      path: /fluxcd/azure/
      requiresAuth: false
      secret:
        usernameKey: ""
        passwordKey: ""