{{- if eq .Values.components.analytics_workspace_management.state "enabled" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-applier
  namespace: {{ .Values.components.analytics_workspace_management.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux.applier.binding.name" .Values.components.analytics_workspace_management }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: {{ .Values.components.analytics_workspace_management.namespace }}
{{- end -}}