{{- if eq .Values.components.jupyter_hub.state "enabled" -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
  labels:
    kubernetes.io/metadata.name: {{ .Values.components.jupyter_hub.namespace }}
    lsc-sde.io/injectJupyterCertificates: "true"
  name: {{ .Values.components.jupyter_hub.namespace }}
{{- end -}}