{{- if .Values.components.jupyter_hub.enabled -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jupyter
spec:
  dependsOn:
  - name: lscsde-workspace-mgr
  force: false
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: jupyter
    namespace: {{ .Release.Namespace }}
  timeout: 1m0s
  wait: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
    - kind: ConfigMap
      name: deployment-config
    - kind: ConfigMap
      name: environment-configuration
{{- end -}}