{{- if eq .Values.components.metrics_server.state "enabled" -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    kubernetes.io/metadata.name: {{ printf "%s%s" .Values.components.metrics_server.namespace .Values.naming.suffix }}
  name: {{ printf "%s%s" .Values.components.metrics_server.namespace .Values.naming.suffix }}
{{- end -}}