{{- if eq .Values.components.metrics_server.state "enabled" -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: {{ .Values.components.metrics_server.namespace }}
spec:
  targetNamespace: {{ .Values.components.metrics_server.namespace }}
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: {{ .Values.components.metrics_server.namespace }}
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
{{- end -}}
