{{- if eq .Values.components.metrics_server.state "enabled" -}}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: {{ printf "%s%s" .Values.components.metrics_server.namespace .Values.naming.suffix }}
spec:
  interval: 5m
  url: {{ .Values.components.metrics_server.chart_url }}
{{- end -}}