{{- if eq .Values.components.metrics_server.state "enabled" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-applier
  namespace: {{ printf "%s%s" .Values.components.metrics_server.namespace .Values.naming.suffix }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s%s" (include "flux.applier.binding.name" .Values.components.metrics_server) .Values.naming.suffix }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: {{ printf "%s%s" .Values.components.metrics_server.namespace .Values.naming.suffix }}
{{- end -}}