
{{- if eq .Values.components.guacamole.state "enabled" -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
  labels:
    kubernetes.io/metadata.name: {{ cat .Values.components.guacamole.namespace .Values.naming.suffix }}
    lsc-sde.io/injectJupyterCertificates: "true"
  name: {{ cat .Values.components.guacamole.namespace .Values.naming.suffix }}
{{- end -}}