apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.name" . }}
data:
  environment_dns_prefix: {{ .Values.dns.prefix }}
  environment_dns_suffix: {{ .Values.naming.suffix }}
{{ range $key, $value := .Values.components }}
{{ if hasKey $value "branch"}}
  {{ $key }}_branch: {{ $value.branch }}
{{ end }}
{{ if hasKey $value "chart_version"}}
  {{ $key }}_chart_version: {{ $value.chart_version }}
{{ end }}
{{ if hasKey $value "image"}}
  {{ $key }}_image: {{ $value.image }}
{{ end }}
{{ if hasKey $value "storage_account_lsc"}}
  {{ $key }}_storage_account_lsc: {{ $value.storage_account_lsc }}
{{ end }}
{{ if hasKey $value "storage_account_nw"}}
  {{ $key }}_storage_account_nw: {{ $value.storage_account_nw }}
{{ end }}
{{ if hasKey $value "storage_account_rg"}}
  {{ $key }}_storage_account_rg: {{ $value.storage_account_rg }}
{{ end }}
{{ if hasKey $value "storage_account_sub_id"}}
  {{ $key }}_storage_account_sub_id: {{ $value.storage_account_sub_id }}
{{ end }}
{{ if hasKey $value "key_vault"}}
  {{ $key }}_key_vault: {{ $value.key_vault }}
{{ end }}
{{ end }}

  