apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ cat "deployment-namespaces" .Values.naming.suffix }}
data:
  ohdsi_namespace: {{ cat .Values.components.ohdsi.namespace .Values.naming.suffix }}
  secrets_distributor_namespace: {{ cat .Values.components.secrets_distributor.namespace .Values.naming.suffix }}
  certmanager_namespace: {{ cat .Values.components.cert_manager.namespace .Values.naming.suffix }}
  trustmanager_namespace: {{ cat .Values.components.trust_manager.namespace .Values.naming.suffix }}
  github_runner_namespace: {{ cat .Values.components.github_runner.namespace .Values.naming.suffix }}
  aks_dns_namespace: {{ cat .Values.components.aks_dns.namespace .Values.naming.suffix }}
  nginx_namespace: {{ cat .Values.components.ingress_nginx.namespace .Values.naming.suffix }}
  keda_namespace: {{ cat .Values.components.keda.namespace .Values.naming.suffix }}
  jupyter_namespace: {{ cat .Values.components.jupyter_hub.namespace .Values.naming.suffix }}
  analytics_workspace_management_namespace: {{ cat .Values.components.analytics_workspace_management.namespace .Values.naming.suffix  }}
  metrics_server_namespace: {{ cat .Values.components.metrics_server.namespace .Values.naming.suffix }}
  guacamole_namespace: {{ cat .Values.components.guacamole.namespace .Values.naming.suffix }}
