apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.name" . }}
data:
  environment_dns_prefix: {{ .Values.dns.prefix }}
  environment_dns_suffix: {{ .Values.naming.suffix }}
{{ range $key, $value := .Values.components }}
{{ if hasKey $value "branch"}}
  {{ $key }}_branch: {{ $value.branch }}
{{ end }}
{{ if hasKey $value "chart_version"}}
  {{ $key }}_char_version: {{ $value.branch }}
{{ end }}
{{ if hasKey $value "image"}}
  {{ $key }}_image: {{ $value.image }}
{{ end }}
{{ end }}

  