apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "deployment-namespaces%s" .Values.naming.suffix }}
data:
{{ range $key, $value := .Values.components }}
{{ if hasKey $value "namespace"}}
  {{ $key }}_namespace: {{ $value.namespace }}
{{ end }}
{{ end }}