{{- if eq .Values.components.aks_dns.state "enabled" -}}
{{- if eq .Values.azure.state "enabled" -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ printf "aks-dns-operator%s" .Values.naming.suffix }}
  annotations:
    lsc-sde.nhs.uk/definitionVersion: "1.0.1"
spec:
  targetNamespace: lscsde
  releaseName: {{ printf "aks-dns-operator%s" .Values.naming.suffix }}
  chart:
    spec:
      chart: aks-dns-operator
      version: {{ .Values.components.aks_dns.chart_version }}
      sourceRef:
        kind: HelmRepository
        name: {{ printf "lsc-sde%s" .Values.naming.suffix }}
        namespace: {{ .Release.Namespace }}
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  - kind: ConfigMap
    name: {{ printf "aks-dns-operator-config%s" .Values.naming.suffix }}
{{- end -}}
{{- end -}}