{{- if eq .Values.components.cert_manager.state "enabled" -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
  labels:
    kubernetes.io/metadata.name: {{ .Values.components.cert_manager.namespace }}
  name: {{ .Values.components.cert_manager.namespace }}
{{- end -}}