{{- if eq .Values.components.cert_manager.state "enabled" -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ cat "certmanager-post-helm" .Values.naming.suffix }}
spec:
  dependsOn:
  - name: certmanager
  force: false
  interval: 1m0s
  path: ./post-helm
  prune: true
  retryInterval: 1m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: {{ cat "certmanager" .Values.naming.suffix }}
    namespace: {{ .Release.Namespace }}
  timeout: 1m0s
  wait: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
    - kind: ConfigMap
      name: deployment-config
    - kind: ConfigMap
      name: environment-configuration
{{- end -}}