{{- if eq .Values.components.cert_manager.state "enabled" -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager
spec:
  force: false
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: certmanager
    namespace: {{ .Release.Namespace }}
  timeout: 1m0s
  wait: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
    - kind: ConfigMap
      name: {{ include "config.name" . }}
    - kind: ConfigMap
      name: environment-configuration
    - kind: ConfigMap
      name: deployment-namespaces
{{- end -}}